# プロジェクトの識別子（SonarQubeサーバー上で設定したもの）
sonar.projectKey=kunisan222_sandbox-sonarcloud

# 解析対象のソースコードがあるフォルダ（カレントディレクトリなら . ）
sonar.sources=.

# 先ほどのエラーに関連する、build-wrapperの出力先
sonar.cfamily.build-wrapper-output=bw-output

# エンコーディング
sonar.sourceEncoding=UTF-8
